baseurl: "/klantinteracties"
apiname: "API-standaarden voor Klantinteracties"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geopend.
nav:
  - title: Klantinteracties
    subnav:
      - title: Main
        path: /
      - title: Productvisie
        path: /productvisie
      - title: Quickstart
        path: /quickstart
      - title: Architectuur
        path: /architectuur
  - title: Informatiemodel
      subnav:
      - title: Basisterminologie
        path: /informatiemodel/basisterminologie
      - title: Semantisch model (SIM)
        path: /semantisch_model
      - title: Uitwisselingsmodel (UGM)
        path: /uitwisselingsmodel
      - title: Gegevenswoordenboek
        path: /gegevenswoordenboek
  - title: API-familie
      subnav:
      - title: API X
        path: /api_x
      - title: API Y
        path: /api_y
      - title: Referentieimplementatie
        path: /referentieimplementatie
  - title: Achtergrond documentatie
      subnav: 
      - title: Aanbevelingen
        path: /achtergronddocumentatie/aanbevelingen
  - title: Specificaties Klanten API (IO)
    subnav:
      - title: Specificaties
        path: /api-standaarden/klanten/specificaties
      - title: Klanten API (redoc)
        path: /redoc-io-klanten
      - title: Referentieimplementatie
        path: /api-standaarden/klanten/referentieimplementatie
  - title: Specificaties Contactmomenten API (IO)
    subnav:
#      - title: Specificaties
#        path: /api-standaarden/klanten/specificaties
      - title: Contactmomenten API (redoc)
        path: /redoc-io-contactmomenten
#      - title: Referentieimplementatie
#        path: /api-standaarden/klanten/referentieimplementatie
#  - title: Specificaties Verzoeken API (IO)
#    subnav:
#      - title: Specificaties
#        path: /api-standaarden/klanten/specificaties
#      - title: Verzoeken API (redoc)
#        path: /redoc-io-verzoeken
#      - title: Referentieimplementatie
#        path: /api-standaarden/klanten/referentieimplementatie

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jemoji

github: VNG-Realisatie/klantinteracties

theme: jekyll-theme-time-machine

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

project_name: API-standaarden voor Klantinteracties

standard_family: nvt
