baseurl: "/klantinteracties"
apiname: "API-standaarden voor Klantinteracties"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geopend.
nav:
  - title: Klantinteracties
    subnav:
      - title: Main
        path: /
      - title: Productvisie
        path: /productvisie
      - title: Quickstart
        path: /quickstart
      - title: Architectuur
        path: /architectuur/architectuur
  - title: Informatiemodel
    subnav:
      - title: Basisterminologie
        path: /informatiemodel/basisterminologie
      - title: Semantisch model (SIM)
        path: /informatiemodel/semantisch_model
      - title: Uitwisselingsmodel (UGM)
        path: /informatiemodel/uitwisselingsmodel
      - title: Gegevenswoordenboek
        path: /informatiemodel/gegevenswoordenboek
  - title: API-familie X
    subnav:
      - title: Specificaties in Swagger
        path: https://petstore.swagger.io/?url=https://klantinteracties/docs/api-familie-x/specificatie/openapi.yaml
      - title: Specificaties in Redoc
        path: /redoc
      - title: Gedragsspecificaties
        path: /api-familie-x/gedragsspecificaties
      - title: Referentieimplementatie
        path: /api-familie-x/referentieimplementatie
  - title: Achtergrond documentatie
    subnav: 
      - title: Aanbevelingen
        path: /achtergronddocumentatie/aanbevelingen
      - title: Besluiten
        path: /achtergronddocumentatie/besluiten
      - title: Cases
        path: /achtergronddocumentatie/cases
      - title: Functies
        path: /achtergronddocumentatie/funties
      - title: Vraagstukken
        path: /achtergronddocumentatie/vraagstukken    
  - title: Vraag en Antwoord
    subnav:
      - title: Veel gestelde vragen
        path: /veelgesteldevragen
      - title: Contact 
        path: /contact


plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jemoji

github: VNG-Realisatie/klantinteracties

theme: jekyll-theme-time-machine

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

project_name: API-standaarden voor Klantinteracties

standard_family: nvt
